version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/html
    depends_on:
      - php
    ports:
      - "80:80"
  php:
    image: bitnami/php-fpm
    volumes:
      - ./src:/www
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "6612:3306"

volumes:
  mariadb:
